export const SET_RANDOM_QUOTE_BY_CHARACTER = "SET_RANDOM_QUOTE_BY_CHARACTER";
export const IS_ERROR_QUOTE = "IS_ERROR_QUOTE";
export const IS_LOADER_QUOTE = "IS_LOADER_QUOTE";
export const SET_RANDOM_QUOTE = "SET_RANDOM_QUOTE";
